### PR TITLE
Added support for SPM

### PR DESCRIPTION
**Pull request by rsmoz**

### CODE REVIEW

**Comment by jehna** [comment]
Could we use [Target](https://github.com/apple/swift-package-manager/blob/master/Documentation/Package.swift.md) to include the files from the original `VerbalExpressions/` folder?

> The targets are named how your subdirectories are named.

**Comment by rsmoz** [comment]
I was under the impression specifying a target was actually meant actually for different compilation targets, not for adding source files to the compilation.

**Comment by jehna** [comment]
At some level I disagree with the [Convention-Based Configuration](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageManagerCommunityProposal.md#convention-based-configuration) of SPM, because if all the package managers had their own conventions, a library could only exist in one package manager at a time.

Could we use a symbolic link? At least the [.isDirectory](https://github.com/apple/swift-package-manager/blob/master/Sources/sys/Path.swift#L199-L201) [should work](https://github.com/apple/swift-package-manager/blob/master/Sources/dep/Manifest%2BconfigureTargets.swift#L56) with symlinks, if I understood correctly.

**Comment by rsmoz** [comment]
It's very common for software projects to have some directory to the effect of "sources" but if you're fundamentally opposed to adopting any convention from a package manager, I understand. In practice, especially for this repository, I think it makes no difference. But I understand the ideological opposition.

You may do as you please with my PR'd code, but I'm probably done with commits to this.

**Comment by rsmoz** [comment]
I may be mistaken on how SPM works, that might be something worth pursuing. If I figure something out with SPM I'll contribute it.

**Comment by rsmoz** [comment]
Have actually realized you don't need Sources. Not quite done yet.

**Comment by rsmoz** [comment]
Seems like excludes are not working. Might have to chalk that up to SPM being in beta.
¯_(ツ)_/¯

**Comment by rsmoz** [comment]
Apparently SPM will allow custom folder structures soon.

**Comment by rsmoz** [comment]
Rebased. Will wait for SPM to support custom source folders, which apparently will be soonish.

**Pull request closed without merging**
